console.log("ALARMA")
console.log("ENTRADA:Programar alarma")
console.log("PROCESO:Definir hora de despertar")
console.log("SALIDA:Suena alarma y despertar")

console.log("DESAYUNO")
console.log("ENTRADA:Definir que hacer para desayunar")
console.log("PROCESO:Prender la estufa,poner la leche para el café,poner el pan en la tostadora")
console.log("SALIDA:poner el café en el vaso con azucar y agregar la leche caliente, servir las tostadas en un plato con mermelada")

console.log("CEPILLARSE LOS DIENTES")
console.log("ENTRADA:Enjuagar los dientes y ponerle crema al cepillo")
console.log("PROCESO:cepillar los dientes ")
console.log("SALIDA:enjuagar los dientes y lavar el cepillo")

console.log("VER TELEVISION")
console.log("ENTRADA:Conectar el T.V y cojer el control remoto")
console.log("PROCESO:Encender el T.V , abrir Netflix, poner la serie ")
console.log("SALIDA:Ponerle PLAY , para ver una excelente serie")

console.log("CONECTARSE AL SISTEMA")
console.log("ENTRADA:Desbloquear la pantalla")
console.log("PROCESO:abrir el sistema, poner usuario,poner clave y darle enter")
console.log("SALIDA:Poder conectarse a la RED para entrar a trabajar")

